PropImitationHooks: Simplify reflection methods and remove conflicting task stack listeners
* the task stack listeners was triggerring various crashes due to permission denials [1]
* Also make setPropValue cover all class and types to avoid erros during forEach((k, v) -> setPropValue(k, v))

[1]
Permission Denial: registerTaskStackListener() from pid=3807, uid=10303 requires android.permission.MANAGE_ACTIVITY_TASKS
02-19 07:38:21.200  1610  2649 W ActivityTaskManager: Permission Denial: getFocusedRootTaskInfo() from pid=3807, uid=10303 requires android.permission.MANAGE_ACTIVITY_TASKS
02-19 07:38:21.201  3807  3894 E PropImitationHooks: Unable to get top activity!
02-19 07:38:21.201  3807  3894 E PropImitationHooks: java.lang.SecurityException: Permission Denial: getFocusedRootTaskInfo() from pid=3807, uid=10303 requires android.permission.MANAGE_ACTIVITY_TASKS
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.os.Parcel.createException(Parcel.java:3045)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.os.Parcel.readException(Parcel.java:3028)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.os.Parcel.readException(Parcel.java:2970)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.app.IActivityTaskManager$Stub$Proxy.getFocusedRootTaskInfo(IActivityTaskManager.java:2702)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.internal.util.PropImitationHooks.isGmsAddAccountActivityOnTop(PropImitationHooks.java:302)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.internal.util.PropImitationHooks.shouldTryToSpoofDevice(PropImitationHooks.java:278)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.internal.util.PropImitationHooks.onEngineGetCertificateChain(PropImitationHooks.java:377)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.security.keystore2.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:198)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at java.security.KeyStore.getCertificateChain(KeyStore.java:1108)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at anac.a(PG:79)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at tvb.a(PG:24)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at sdh.a(PG:760)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at asis.d(PG:3)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at asiu.run(PG:42)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at myf.run(PG:393)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at java.lang.Thread.run(Thread.java:1012)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: Caused by: android.os.RemoteException: Remote stack trace:
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.server.wm.ActivityTaskManagerService.enforceTaskPermission(ActivityTaskManagerService.java:3328)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.server.wm.ActivityTaskManagerService.getFocusedRootTaskInfo(ActivityTaskManagerService.java:1995)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1402)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at com.android.server.wm.ActivityTaskManagerService.onTransact(ActivityTaskManagerService.java:5615)
02-19 07:38:21.201  3807  3894 E PropImitationHooks: 	at android.os.Binder.execTransactInternal(Binder.java:1358)
02-19 07:38:21.201  3807  3894 E PropImitationHooks:
02-19 07:38:21.201  3807  3894 D PropImitationHooks: Skip spoofing build for GMS, because GmsAddAccountActivityOnTop!
java.lang.SecurityException: Permission Denial: registerTaskStackListener() from pid=3807, uid=10303 requires android.permission.MANAGE_ACTIVITY_TASKS

Original commit:
https://github.com/minaripenguin/android_frameworks_base/commit/48b505efc2664a42d82080bfced61f143eed3cdd

Change-Id: Icf6e2cebbae32279800bb3681678209f1caa3137
Signed-off-by: minaripenguin <minaripenguin@users.noreply.github.com>
Signed-off-by: someone5678 <someone5678@users.noreply.github.com>